const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization',
};

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);

    // 1. Handle CORS Preflight OPTIONS requests
    if (request.method === 'OPTIONS') {
      return new Response(null, {
        status: 204,
        headers: corsHeaders,
      });
    }

    // 2. AI Invoice Generation Route (Google Gemini API)
    if (url.pathname === '/api/ai/generate-invoice') {
      if (request.method !== 'POST') {
        return new Response(
          JSON.stringify({
            status: 'error',
            message: 'Method not allowed. Use POST.',
          }),
          {
            status: 405,
            headers: {
              ...corsHeaders,
              'Content-Type': 'application/json',
            },
          }
        );
      }

      try {
        const geminiApiKey = env.GEMINI_API_KEY;
        if (!geminiApiKey || !geminiApiKey.trim()) {
          return new Response(
            JSON.stringify({
              status: 'error',
              message: 'Gemini API key is not configured. Please set GEMINI_API_KEY in Worker secrets.',
            }),
            {
              status: 500,
              headers: {
                ...corsHeaders,
                'Content-Type': 'application/json',
              },
            }
          );
        }

        let body = {};
        try {
          body = await request.json();
        } catch {
          body = {};
        }

        const promptText = `You are a professional invoice generator. Based on the following details or prompt, generate a complete, well-structured invoice.
Return ONLY valid JSON (no markdown formatting, no code blocks) with this structure:
{
  "invoice_number": "INV-001",
  "date": "YYYY-MM-DD",
  "due_date": "YYYY-MM-DD",
  "issueDate": "YYYY-MM-DD",
  "dueDate": "YYYY-MM-DD",
  "clientName": "client_name",
  "clientEmail": "client_email",
  "clientCompany": "client_company",
  "from": { "name": "Business Name", "email": "billing@example.com" },
  "to": { "name": "client_name", "email": "client_email" },
  "items": [
    {
      "description": "Item description",
      "quantity": 1,
      "price": 100,
      "unitPrice": 100,
      "amount": 100,
      "total": 100
    }
  ],
  "currency": "USD",
  "subtotal": 100,
  "taxRate": 0,
  "tax": 0,
  "discount": 0,
  "total": 100,
  "notes": "Thank you for your business.",
  "terms": "Due upon receipt"
}

Invoice details or prompt: ${typeof body === 'string' ? body : JSON.stringify(body)}`;

        const modelsToTry = ['gemini-2.5-flash', 'gemini-3.6-flash', 'gemini-3.5-flash'];
        let geminiData = null;
        let lastErrorMsg = '';

        for (const model of modelsToTry) {
          try {
            const geminiResponse = await fetch(
              `https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent?key=${geminiApiKey.trim()}`,
              {
                method: 'POST',
                headers: {
                  'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                  contents: [
                    {
                      parts: [
                        {
                          text: promptText,
                        },
                      ],
                    },
                  ],
                  generationConfig: {
                    temperature: 0.7,
                    responseMimeType: 'application/json',
                  },
                }),
              }
            );

            const data = await geminiResponse.json();
            if (geminiResponse.ok && data?.candidates?.[0]?.content?.parts?.[0]?.text) {
              geminiData = data;
              break;
            } else {
              lastErrorMsg =
                data?.error?.message ||
                data?.message ||
                `Gemini API returned status ${geminiResponse.status}`;
            }
          } catch (fetchErr) {
            lastErrorMsg = fetchErr?.message || 'Network error while calling Gemini API';
          }
        }

        if (!geminiData) {
          return new Response(
            JSON.stringify({
              status: 'error',
              message: lastErrorMsg || 'Failed to generate invoice with Gemini AI',
            }),
            {
              status: 500,
              headers: {
                ...corsHeaders,
                'Content-Type': 'application/json',
              },
            }
          );
        }

        const rawText = geminiData.candidates?.[0]?.content?.parts?.[0]?.text;
        if (!rawText) {
          return new Response(
            JSON.stringify({
              status: 'error',
              message: 'No content was generated by Gemini AI.',
            }),
            {
              status: 500,
              headers: {
                ...corsHeaders,
                'Content-Type': 'application/json',
              },
            }
          );
        }

        // Clean out any stray markdown fence if present
        let cleanedJson = rawText.trim();
        if (cleanedJson.startsWith('```json')) {
          cleanedJson = cleanedJson.replace(/^```json\s*/, '').replace(/\s*```$/, '');
        } else if (cleanedJson.startsWith('```')) {
          cleanedJson = cleanedJson.replace(/^```\s*/, '').replace(/\s*```$/, '');
        }

        const parsedInvoice = JSON.parse(cleanedJson);

        return new Response(
          JSON.stringify({
            status: 'success',
            invoice: parsedInvoice,
          }),
          {
            status: 200,
            headers: {
              ...corsHeaders,
              'Content-Type': 'application/json',
            },
          }
        );
      } catch (err) {
        return new Response(
          JSON.stringify({
            status: 'error',
            message: err.message || 'An error occurred while generating invoice with AI.',
          }),
          {
            status: 500,
            headers: {
              ...corsHeaders,
              'Content-Type': 'application/json',
            },
          }
        );
      }
    }

    // 3. Flutterwave Payment Initialization Route
    if (url.pathname === '/api/flutterwave/initialize') {
      if (request.method !== 'POST') {
        return new Response(
          JSON.stringify({
            status: 'error',
            message: 'Method not allowed. Use POST.',
          }),
          {
            status: 405,
            headers: {
              ...corsHeaders,
              'Content-Type': 'application/json',
            },
          }
        );
      }

      try {
        const secretKey = env.FLUTTERWAVE_SECRET_KEY;
        if (!secretKey || !secretKey.trim()) {
          return new Response(
            JSON.stringify({
              status: 'error',
              message: 'Flutterwave secret key is not configured in Worker environment.',
            }),
            {
              status: 500,
              headers: {
                ...corsHeaders,
                'Content-Type': 'application/json',
              },
            }
          );
        }

        const body = await request.json();

        // Ensure Flutterwave v3 required fields are present and properly structured
        const tx_ref = body.tx_ref || `INV-${Date.now()}-${Math.random().toString(36).substring(2, 8).toUpperCase()}`;
        const amount = body.amount || (body.plan === 'enterprise' ? 15.99 : 9.99);
        const currency = body.currency || 'USD';
        const customer = body.customer || {
          email: body.email || 'customer@example.com',
          name: body.name || 'Subscriber',
          phonenumber: body.phoneNumber || body.phone_number || '',
        };
        const redirect_url = body.redirect_url || body.callbackUrl || `${url.origin}/billing?flw_callback=1`;
        const payment_options = body.payment_options || body.paymentOptions || 'card,mobilemoney,ussd,banktransfer';
        const customizations = body.customizations || {
          title: body.plan ? `InvoiceFlow ${body.plan.toUpperCase()} Plan` : 'Invoice Payment',
          description: `Payment for ${body.plan || 'InvoiceFlow'}`,
          logo: `${url.origin}/favicon.ico`,
        };

        const flwPayload = {
          tx_ref,
          amount,
          currency,
          redirect_url,
          payment_options,
          customer,
          customizations,
          meta: body.meta || body.metadata || { plan: body.plan, mode: body.mode },
        };

        // Forward request to Flutterwave Standard Checkout API
        const flwResponse = await fetch('https://api.flutterwave.com/v3/payments', {
          method: 'POST',
          headers: {
            Authorization: `Bearer ${secretKey.trim()}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(flwPayload),
        });

        const flwData = await flwResponse.json();

        return new Response(JSON.stringify(flwData), {
          status: flwResponse.status,
          headers: {
            ...corsHeaders,
            'Content-Type': 'application/json',
          },
        });
      } catch (err) {
        return new Response(
          JSON.stringify({
            status: 'error',
            message: err.message || 'Internal server error while initializing Flutterwave payment.',
          }),
          {
            status: 500,
            headers: {
              ...corsHeaders,
              'Content-Type': 'application/json',
            },
          }
        );
      }
    }

    // 4. Example API route demonstrating access to env variables & secrets
    if (url.pathname === '/api/hello') {
      const environment = env.ENVIRONMENT || 'development';
      const customMessage = env.CUSTOM_MESSAGE || 'Hello from Cloudflare Worker!';

      return new Response(
        JSON.stringify({
          message: customMessage,
          environment,
          timestamp: new Date().toISOString(),
        }),
        {
          headers: {
            ...corsHeaders,
            'Content-Type': 'application/json',
          },
        }
      );
    }

    // 5. Attempt to serve static assets if ASSETS binding is available
    if (env.ASSETS) {
      const response = await env.ASSETS.fetch(request);
      if (response.status !== 404) {
        return response;
      }
    }

    // 6. 404 Not Found for unhandled routes
    return new Response(
      JSON.stringify({
        error: 'Not Found',
        message: `Route ${url.pathname} not found.`,
      }),
      {
        status: 404,
        headers: {
          ...corsHeaders,
          'Content-Type': 'application/json',
        },
      }
    );
  },
};
